### ISSUE TITLE
websocket url有什么用

### ISSUE THREAD

**Issue by majingfenggithub** [stavyan/TinyShop-UniApp#14]
现在的websocket是不是根本就没有用起来，查了下代码根本就没用起来

**Comment by stavyan** [comment]
websocket url 客服版本才用得到 开源版本可以不用考虑这个地址的

**Comment by majingfenggithub** [comment]
能共享一份如何连接websocket的代码么，用的是stomp吗？我想基于你的框架自定义一个应用，不是用于商店

**Comment by stavyan** [comment]
用的是swoole 可以自己读读swoole文档 不难上手的 框架相关问题可以加我们的技术交流群
