### ISSUE TITLE
项目启动报错

### ISSUE THREAD

**Issue by banli** [stavyan/TinyShop-UniApp#2]
error  in ./src/components/uni-icons/uni-icons-rate.vue?vue&type=style&index=0&id=6bfa2fdc&lang=scss&scoped=true&

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Invalid argument(s): Unsupported output style "nested".

**Comment by stavyan** [comment]
1. 如果是HBuilderX导入运行的话 菜单栏 -> 工具 -> 插件安装 找到并安装 scss/sass编译 插件。
2 .如果使用vue-cli 运行方式 在clone项目后按照文档运行说明运行项目。
