### ISSUE TITLE
请问下如果有不同的基地址  请求的时候baseUrl 怎么传？

### ISSUE THREAD

**Issue by chending1994** [stavyan/TinyShop-UniApp#25]
请问下如果基地址不同  请求的时候baseUrl 怎么传？

**Comment by stavyan** [comment]
baseUrl是api地址的前缀 如果有多个基地址 可以在src/request里面修改逻辑引用不同的基地址

**Comment by chending1994** [comment]
> baseUrl是api地址的前缀 如果有多个基地址 可以在src/request里面修改逻辑引用不同的基地址

ok 知道了 谢谢
