### ISSUE TITLE
请问下引入upx 的好处是什么？为什么要使用upx

### ISSUE THREAD

**Issue by huangyuhui123** [stavyan/TinyShop-UniApp#6]

**Comment by stavyan** [comment]
可以看看文档这篇文章 https://uniapp.dcloud.io/frame?id=%e5%b0%ba%e5%af%b8%e5%8d%95%e4%bd%8d
https://ask.dcloud.net.cn/article/36130
不过最新uniapp的版本已经不推荐使用upx 而是推荐使用rpx
