### ISSUE TITLE
首页的浮动分类标题上方有bug

### ISSUE THREAD

**Issue by Aton5859** [stavyan/TinyShop-UniApp#9]
![微信图片_20200731134033](https://user-images.githubusercontent.com/28555389/89003864-72bcf380-d333-11ea-8d4f-d37c9374fc98.png)
![微信图片_20200731134039](https://user-images.githubusercontent.com/28555389/89003871-76e91100-d333-11ea-90c0-82e273dec197.png)

**Comment by stavyan** [comment]
已修复
